import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { failure, success } from "../shared.ts";
import { createBinaryFile, importChatGptFile, readMedia } from "./binary.ts";
import { createTextFile, deleteTextFile, listDirectory, listWorkspaces, patchTextFile, readTextFile, writeTextFile } from "./workspace.ts";

/** 注册本地受授权工作区的文件工具。 */
export function registerFileTools(server: McpServer, writesEnabled: boolean): void {
  server.registerTool("workspace_list", { title: "列出授权工作区", description: "列出可由远程 ChatGPT 访问的显式或默认工作区。", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true } }, async () => { try { return success(await listWorkspaces()); } catch (error) { return failure(error); } });
  server.registerTool("file_list", { title: "列出工作区文件", description: "列出授权工作区内目录的直接子项，不跟随符号链接。", inputSchema: { workspace: z.string().min(1), path: z.string().optional().default(".") }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true } }, async ({ workspace, path }) => { try { return success(await listDirectory(workspace, path)); } catch (error) { return failure(error); } });
  server.registerTool("file_read", { title: "读取工作区文件", description: "读取授权工作区内不超过 512 KiB 的 UTF-8 文件，并返回内容哈希。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true } }, async ({ workspace, path }) => { try { return success(await readTextFile(workspace, path)); } catch (error) { return failure(error); } });
  server.registerTool("media_read", { title: "查看本地图片或音频", description: "从授权工作区读取不超过 4 MiB 的 PNG、JPEG、WebP、WAV 或 MP3，并以 MCP 媒体内容返回。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true } }, async ({ workspace, path }) => { try { return await readMedia(workspace, path); } catch (error) { return failure(error); } });
  if (!writesEnabled) return;
  server.registerTool("file_create", { title: "创建工作区文件", description: "在已有父目录下创建新的 UTF-8 文件；目标已存在时拒绝覆盖。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1), content: z.string() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false } }, async ({ workspace, path, content }) => { try { return success(await createTextFile(workspace, path, content)); } catch (error) { return failure(error); } });
  server.registerTool("file_create_binary", { title: "创建本地二进制文件", description: "将不超过 1 MiB 的 Base64 数据解码并在授权工作区创建新文件；拒绝覆盖。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1), data_base64: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false } }, async ({ workspace, path, data_base64 }) => { try { return success(await createBinaryFile(workspace, path, data_base64)); } catch (error) { return failure(error); } });
  server.registerTool("file_import", { title: "保存 ChatGPT 文件到本地", description: "把 ChatGPT 生成或上传的文件保存到授权工作区的新路径；拒绝覆盖。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1), file: z.object({ download_url: z.string().url(), file_id: z.string().min(1), mime_type: z.string().optional(), file_name: z.string().optional() }) }, _meta: { "openai/fileParams": ["file"] }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ workspace, path, file }) => { try { return success(await importChatGptFile(workspace, path, file)); } catch (error) { return failure(error); } });
  server.registerTool("file_patch", { title: "应用工作区文件补丁", description: "应用由 @@ 区块与空格、+、- 行构成的 Codex 风格上下文补丁；先调用 file_read，并传入其 sha256。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1), patch: z.string().min(1), expected_sha256: z.string().regex(/^[a-f0-9]{64}$/u) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false } }, async ({ workspace, path, patch, expected_sha256 }) => { try { return success(await patchTextFile(workspace, path, patch, expected_sha256)); } catch (error) { return failure(error); } });
  server.registerTool("file_write", { title: "更新工作区文件", description: "以完整 UTF-8 内容更新文件；必须提供最新 file_read 返回的 sha256。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1), content: z.string(), expected_sha256: z.string().regex(/^[a-f0-9]{64}$/u) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false } }, async ({ workspace, path, content, expected_sha256 }) => { try { return success(await writeTextFile(workspace, path, content, expected_sha256)); } catch (error) { return failure(error); } });
  server.registerTool("file_delete", { title: "删除工作区文件", description: "将文件移入工作区 .chatgpt-mcp-trash 回收目录；必须提供最新 file_read 返回的 sha256。", inputSchema: { workspace: z.string().min(1), path: z.string().min(1), expected_sha256: z.string().regex(/^[a-f0-9]{64}$/u) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false } }, async ({ workspace, path, expected_sha256 }) => { try { return success(await deleteTextFile(workspace, path, expected_sha256)); } catch (error) { return failure(error); } });
}
